---
title: "IGD-ADHD SEM MA"
author: "Tamás Nagy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(googlesheets4)
library(metaSEM)
```


```{r}
# Set the estimated correlation between outcomes
est_r <- .5
```

```{r}
# Read and process data
igd_raw <- range_read("1kSmnj8Jy9BydAyrsVJxpTvZSS53tus-aBigIHJujQQY")

igd <-
    igd_raw |> 
    janitor::clean_names() |> 
    # Calculate variance by squaring the standard errors
    transmute(study_name, outcome, z = fishers_z, var_z = std_err_z^2) |> 
    filter(outcome != "Combined") |> 
    mutate(outcome = if_else(outcome == "Inattention", "inat", "hyper")) |> 
    pivot_wider(names_from = outcome, 
                values_from = c(z, var_z),
                id_cols = c(study_name),
                ) |> 
    # Calculate covariance of the two outcomes for each study based on Schwarzer, Carpenter, and Rücker 2015
    mutate(cov_est = sqrt(var_z_hyper) * sqrt(var_z_inat) * est_r) |> 
    drop_na()
```

```{r}
sem_igd <- 
    meta(y = cbind(z_hyper, z_inat),
         v = cbind(var_z_hyper, cov_est, var_z_inat),
         data = igd)

summary(sem_igd)


```


# The correlation between effects on the two outcomes
```{r}
tau.coefs <- coef(sem_igd, select = "random")
tc.mat <- vec2symMat(tau.coefs) 
dimnames(tc.mat)[[1]] <- dimnames(tc.mat)[[2]] <- c("Hyperactivity", 
                                                    "Inattention")

cov2cor(tc.mat) |> 
    as.data.frame() |> 
    rownames_to_column() |> 
    insight::print_html()
```

The following plot shows effect sizes (black dots) and their confidence ellipses (dashed line).
Red diamonds show the univariate effects, blue diamond shows the bivariate effect with confidence interval (blue line).


```{r}
plot(sem_igd, 
     axis.labels = c("Hyperactivity", "Inattention"), 
     randeff.ellipse.col = NULL,
     univariate.arrows.col = NULL,
     univariate.polygon.col = "red",
     estimate.ellipse.col = "blue",
     estimate.col = "blue",
     asp=1,
     main = NULL) +
     abline(h = 0, v = 0)
```



